language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
env:
  global:
  - secure: h5IQJGg1lonw0zNVgXbTFkqfOLy/wQlqv/sq56EthNP+FGeboiDhZqPv9Q7Tag9RHdUoUSbIGq/J1Bld7ihPCLPJh5zYkxoH2EdPZQaWwDuWyjRJmn4ZLq5ycFJ2/fgmXfN1yJp9juv9q5G6n1tYNIrPT/E35z0TDM9R5P/gk9oGtCOQ1o2U7AvbNY+98UPypR2DF3Z5sRz4lTVzqyCK6RloDJiXf/VFWVYY0Z0YtntuZmq3+0Z0dyVh6O5ltfrpSJClIdtmCkzy6SPBKDNpUzmm/gtFhjtCwX6TZKYNnu7Zdyeik8D/f14PnV+71Zrl4W1hl81g1C8ZsLt1ginTGt0jSPB63Le7Q+cxyRmOcx92uwT5957KqnGXgCFj4BfwxFU5qPHiPi9y0ulEIqNZGiX8Pw+ONOmq45n7eOqWHNjjrvdiykIDVb0MYDJfSQVOjQon1SqLPXSaAmKZUY6vyMkgYYyDSAXCs3ufOxiEr5blCkz3A2A0jZlbP1eiXlzQhAdRcRa9SVyYV9fNov2c3ia4DT+WZOFTOVEpBxeCcvrpMYo/UW0fhP8fB3q65oKUSuvKwmqvkxV0yXgtgKNQA0T357ZWK4KNBNM2idwBBNR5171gLJ5DCJ9p3KCohNTl1CtAPFjA7ceUw1qDbruGDRStFFWq5YhMMI45Y5LqDhM=
  - secure: fpEjj0EQH7+vhw8ekxuK7tTWF4Gae4t0cIbOutnrMRS6/WXzi/CWMuZIUWlMvTxX2aLRjVTmn8d8LUAGZOYQ2bmlHLtBo8sE+rWmkyQi5KdXrFM6U+URbQxaif0PDJzsP1H7qZaHemcm+CJDn3RCpsmBxoJ2NC40o+rxAmGUojqOd5sZj2hIa1Lpjmg47Ql9Ahyt8/wKzmjZ1VUJLZr2l6tSnReVZISTKqBsPfNsBNabMhlILy0oUCrHyy8JwdkfPRii2YOkH4vtahBfe3AyYyr/zZC5LC9/JhgjT4r/6UQuOmrqNmbI4f27jQFy0qCaDc+TUw2pKP2RqCrC4cF4do8I/c/fYhk/oaEaSagk34N/Bll5dBwCSOeCiFQ2/QJ5ocAI+cTMeNlcT83EeTNOmcZoYl+g4DZ2ha9dykOgSxgYBqh9H75MtWzwu4ARXTPO9oj1t8dWJ6gbb1Gh0gWwmilreQzNE2i2ULwoO1qcRMY6ORWuhQI5dkABVJJq7cJm5YC0LvPhvMa3cJtQPZ8GljBXBkpSx3bhoAE3GtUvfrWe7WIoUTa302eYVb/6l8e8tT6Rq7DrR1/XjzMzf5w+kVOzj8ev6fjRkeFooQWXmgtS1ceMv0jMqQQrWhjSJi7hFspppLGbeyxm0IWGW4JYai6tuIUZQnYv34Uw1SYqpSg=
